-- ============================================================================
-- 09_league_size.sql  —  League size: default 10, partner-configurable  🟩 CORE
-- ----------------------------------------------------------------------------
-- Product decision (2026-07-01): the standard league is 10 runners, but the
-- size stays partner-configurable per league. `leagues.max_runners` is already
-- a per-league column, so a partner sets their own table size at creation; this
-- migration only:
--   1. Moves the column DEFAULT from 20 → 10 (the new "standard" table).
--   2. Widens the CHECK bound so partners can define larger tables. The old
--      cap was `between 2 and 20`; partners asked to define their own size, so
--      we lift the ceiling to 100 (still a sane guardrail — the standings /
--      leaderboard read path and the trg_league_cap trigger scale fine, and a
--      hard upper bound protects the size-cap trigger from pathological values).
--
-- Existing leagues are UNTOUCHED — their stored max_runners is preserved. Only
-- the default for NEW leagues and the allowed range change.
--
-- IDEMPOTENT: re-running is safe (drop-if-exists then re-add the constraint;
-- set default is naturally idempotent).
--
-- Depends on: 01_schema.sql (public.leagues).
-- ============================================================================

-- 1. New default for newly-created leagues.
alter table public.leagues
  alter column max_runners set default 10;

-- 2. Widen the allowed range (2 .. 100). Drop the old constraint first so this
--    is safe to re-run and doesn't depend on the old bound value.
do $$
declare
  v_conname text;
begin
  -- Find whatever CHECK constraint currently bounds max_runners (the name is
  -- auto-generated by Postgres, e.g. leagues_max_runners_check).
  select con.conname into v_conname
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace nsp on nsp.oid = rel.relnamespace
  where nsp.nspname = 'public'
    and rel.relname = 'leagues'
    and con.contype = 'c'
    and pg_get_constraintdef(con.oid) ilike '%max_runners%';

  if v_conname is not null then
    execute format('alter table public.leagues drop constraint %I', v_conname);
  end if;
end
$$;

alter table public.leagues
  add constraint leagues_max_runners_check
  check (max_runners between 2 and 100);

-- ----------------------------------------------------------------------------
-- Verification (run manually):
--   select column_default from information_schema.columns
--     where table_schema='public' and table_name='leagues' and column_name='max_runners';
--   -- expect: 10
--   select pg_get_constraintdef(oid) from pg_constraint
--     where conname='leagues_max_runners_check';
--   -- expect: CHECK ((max_runners >= 2) AND (max_runners <= 100))
-- ----------------------------------------------------------------------------
